inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v0801b/v0801b-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_concat_more_comparable_deep_activation.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v0801b-bb3
method:
  load_checkpoint: v0601b-bb3
  load_checkpoint_if_big_seed: v0701b-bb3
