inherit:
  - artifacts/config/v0200/v0200-_default.yaml
  - artifacts/config/v020x_benchmarks/v0701c/v0701c-_base.yaml
  - artifacts/config/v0200/methods/clean/clean_sac_concat_more_comparable_deep_activation.yaml




meta:
  run_name: v0701c-bb3
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
