inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v0801a/v0801a-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_other_canonical_flap_eval_ctx.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v0801a-x3
method:
  load_checkpoint: v0601a-x3
  load_checkpoint_if_big_seed: v0701a-x3
