inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v0861a/v0861a-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_adapter_v2_less.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v0861a-fc10
method:
  load_checkpoint: v0661a-fc10
  load_checkpoint_if_big_seed: v0761a-fc10
mymethod:
  args:
    actor_act_at_end: true
