inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v0861a/v0861a-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_adapter_v2_less.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v0861a-fc7

method:
  args: 
    policy_params:
      hypernetwork_kwargs:
        put_adapter_at_start: True
        put_adapter_at_end: True
        hnet_kwargs:
          threshold_to_assert_sizes: 20

  load_checkpoint: v0661a-fc7
  load_checkpoint_if_big_seed: v0761a-fc7
