inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v1608_9b/v1608_9b-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_adapter_v1_less.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v1608_9b-fb3

train:
  context_encoder:
    args:
      context_dimension: 11
      extra_dimensions: 10