inherit:
  - artifacts/config/v0200/v0200-_default.yaml
  - artifacts/config/v020x_benchmarks/v0674b/v0674b-_base.yaml
  - artifacts/config/v0200/methods/clean/clean_sac_adapter_v1_no_hypernetwork.yaml




meta:
  run_name: v0674b-s3
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
