env:
  args:
    force_mag: 100
  name: ComplexODEBoundedReward
eval:
  context_file:
  - artifacts/config/v0200/contexts/ode/eval/extended_short_eval_good_5.yaml
  episodes: 2005
infra:
  cores: 8
  gpus: auto
  seeds: 8
meta:
  experiment_name: v1608_2b
  is_clean_rl: true
  message: GenRLise(.; ComplexODEBoundedReward)
  run_name: v1608_2b-_base
train:
  checkpoint_frequency: 100000
  context_encoder:
    args:
      noise:
        type: gaussian
        sigma: 0.2
        mean: 1.0
      context_dimension: 2
      extra_dimensions: 1
    base:
      args:
        context_dimension: 1
        max:
        - 5
        min:
        - 0
      name: Normalised
    name: DummyDimensionGaussian
  context_file: artifacts/config/v0200/contexts/ode/train/very_sparse_ode_neg55_all_state.yaml
  do_train: true
  steps: 300000
