inherit:
  - artifacts/config/v0200/v0200-_default.yaml
  - artifacts/config/v020x_benchmarks/v0711b/v0711b-_base.yaml
  - artifacts/config/v0200/methods/clean/clean_sac_adapter_contextualize_v12_base.yaml




meta:
  run_name: v0711b-u3
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
