inherit:
  - artifacts/config/v0200/v0200-_default.yaml
  - artifacts/config/v020x_benchmarks/v0783b/v0783b-_base.yaml
  - artifacts/config/v0200/methods/clean/clean_sac_adapter_v1_less.yaml

train:
  context_file: artifacts/config/v0200/contexts/cartpole_all/masspole/0.yaml


meta:
  run_name: v0783b-fb4
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)

