inherit:
  - artifacts/config/v0200/v0200-_default.yaml
  - artifacts/config/v020x_benchmarks/v0601c/v0601c-_base.yaml
  - artifacts/config/v0200/methods/clean/clean_sac_adapter_v1_less.yaml




meta:
  run_name: v0601c-fb4
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
