inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v1609_3b/v1609_3b-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_adapter_contextualize_v12_base.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v1609_3b-u2
method:
  load_checkpoint: v1609_2b-u2
train:
  context_encoder:
    args:
      context_dimension: 10
      extra_dimensions: 5
