inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v1609_3b/v1609_3b-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_other_canonical_flap_eval_ctx.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v1609_3b-z4
method:
  load_checkpoint: v1609_2b-z4
train:
  context_encoder:
    args:
      context_dimension: 25
      extra_dimensions: 20
