inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v0881c/v0881c-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_unaware_more_comparable_activation.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v0881c-aa6
method:
  load_checkpoint: v0681c-aa6
  load_checkpoint_if_big_seed: v0781c-aa6
train:
  context_file: artifacts/config/v0200/contexts/cartpole_all/masspole/all.yaml
