inherit:
  - artifacts/config/v0200/v0200-_default.yaml
  - artifacts/config/v020x_benchmarks/v0783a/v0783a-_base.yaml
  - artifacts/config/v0200/methods/clean/clean_sac_concat_more_comparable_deep_activation.yaml

train:
  context_file: artifacts/config/v0200/contexts/cartpole_all/masspole/0.yaml


meta:
  run_name: v0783a-bb3
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)

