inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v0805h/v0805h-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_unaware_more_comparable_activation.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v0805h-aa3
method:
  load_checkpoint: v0605h-aa3
  load_checkpoint_if_big_seed: v0705h-aa3
