inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v0805h/v0805h-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_adapter_v1_less.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v0805h-fb4
method:
  load_checkpoint: v0605h-fb4
  load_checkpoint_if_big_seed: v0705h-fb4
