inherit:
  - artifacts/config/v0200/v0200-_default.yaml
  - artifacts/config/v020x_benchmarks/v0681c/v0681c-_base.yaml
  - artifacts/config/v0200/methods/clean/clean_sac_unaware_more_comparable_activation.yaml

train:
  context_file: artifacts/config/v0200/contexts/cartpole_all/masspole/all.yaml


meta:
  run_name: v0681c-aa6
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)

