dims: 5
name: RepeatedContextSampler
how_many_times_run_same_context: 5
desc: 'Test{0.1,10}'
context:
  name: Linspace
  mins: [ 9.8,  1.0,  0.1,  0.1,  10.0]
  maxs: [ 9.8,  1.0,  0.1,  10,  10.0]
  episodes: 301