inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v0805f/v0805f-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_unaware_more_comparable_activation.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v0805f-aa3
method:
  load_checkpoint: v0605f-aa3
  load_checkpoint_if_big_seed: v0705f-aa3
