dims: 2
name: StateAndContext
how_many_times_run_same_context: 4
desc: 'Train[-5,-1,1,5]'
context:
  name: SequenceSampler
  list_of_contexts: [[1, 1], [1, 0], [1, -1], [-1, 1], [-1, 0], [-1, -1], [0, 1], [0, -1], [5, 5], [5, 0], [5, -5], [-5, 5], [-5, 0], [-5, -5], [0, 5], [0, -5]]
state:
  name: SequenceSampler
  list_of_contexts: [[-1.0], [-0.5], [0.5], [1.0]]