env:
  args:
    force_mag: 100
  name: ComplexODEBoundedReward
eval:
  context_file:
  - artifacts/config/v0200/contexts/ode/eval/extended_short_eval_good_5.yaml
  episodes: 2005

infra:
  cores: 8
  gpus: auto
  seeds: 16
  start_seed: 8

meta:
  experiment_name: v1707_2b
  is_clean_rl: true
  message: GenRLise(.; ComplexODEBoundedReward)
  run_name: v1707_2b-_base
train:
  checkpoint_frequency: 100000
  context_encoder:
    args:
      change_val: 0.5
      context_dimension: 2
      extra_dimensions: 1
      fixed_vals: 1
    base:
      args:
        context_dimension: 1
        max:
        - 5
        min:
        - 0
      name: Normalised
    name: DummyDimensions
  context_file: artifacts/config/v0200/contexts/ode/train/very_sparse_ode_neg55_all_state.yaml
  do_train: true
  steps: 1000000
