inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v1709_3b/v1709_3b-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_other_canonical_flap_eval_ctx.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v1709_3b-z1
method:
  load_checkpoint: v1709_2b-z1
train:
  context_encoder:
    args:
      context_dimension: 6
      extra_dimensions: 1
