inherit:
  - artifacts/config/v0200/v0200-_default.yaml
  - artifacts/config/v020x_benchmarks/v0705d/v0705d-_base.yaml
  - artifacts/config/v0200/methods/clean/clean_sac_unaware_more_comparable_activation.yaml




meta:
  run_name: v0705d-aa3
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
