inherit:
  - artifacts/config/v0200/v0200-_default.yaml
  - artifacts/config/v020x_benchmarks/v0661b/v0661b-_base.yaml
  - artifacts/config/v0200/methods/clean/clean_sac_adapter_v1_less.yaml


method:
  args: 
    policy_params:
      hypernetwork_kwargs:
        adapter_layers: [32, 32]

meta:
  run_name: v0661b-fb5
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
