inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v1608_3b/v1608_3b-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_concat_more_comparable_deep_activation.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v1608_3b-bb4
method:
  load_checkpoint: v1608_2b-bb4
train:
  context_encoder:
    args:
      context_dimension: 21
      extra_dimensions: 20
