inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v1788_11d/v1788_11d-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_concat_more_comparable_deep_activation.yaml
meta:
  message: GenRLise(AdapterLess; Cheetah)
  run_name: v1788_11d-bb3
method:
  load_checkpoint: v1578_1d-bb3
