env:
  args:
    force_mag: 10
  name: ComplexODEBoundedReward
eval:
  context_file:
  - artifacts/config/v0200/contexts/proper_ode_two/eval/eval_two_dim_cartesian_mult5.yaml
  episodes: 2205
infra:
  cores: 8
  gpus: auto
  seeds: 16
meta:
  experiment_name: v0874b
  is_clean_rl: true
  message: GenRLise(.; ComplexODEBoundedReward)
  run_name: v0874b-_base
train:
  checkpoint_frequency: 50000
  context_encoder:
    args:
      context_dimension: 2
      max:
      - 5
      - 5
      min:
      - 0
      - 0
    name: Normalised
  context_file: artifacts/config/v0200/contexts/proper_ode_two/train/sparse_just_five_add_one.yaml
  do_train: true
  steps: 0
