inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v0874b/v0874b-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_unaware_more_comparable_activation.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v0874b-aa3
method:
  load_checkpoint: v0674b-aa3
  load_checkpoint_if_big_seed: v0774b-aa3
