inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v0874b/v0874b-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_adapter_v1_no_hypernetwork.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v0874b-s3
method:
  load_checkpoint: v0674b-s3
  load_checkpoint_if_big_seed: v0774b-s3
