inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v1620_3b/v1620_3b-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_adapter_v1_less.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v1620_3b-fb3
method:
  load_checkpoint: v1619_1b-fb3
train:
  context_encoder:
    args:
      context_dimension: 15
      extra_dimensions: 10
