inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v0981c/v0981c-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_unaware_more_comparable_activation.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v0981c-aa5
method:
  load_checkpoint: v0681c-aa5
  load_checkpoint_if_big_seed: v0781c-aa5
train:
  context_file: artifacts/config/v0200/contexts/cartpole_all/masspole/4.yaml
