inherit:
  - artifacts/config/v0200/v0200-_default.yaml
  - artifacts/config/v020x_benchmarks/v0705e/v0705e-_base.yaml
  - artifacts/config/v0200/methods/clean/clean_sac_concat_more_comparable_deep_activation.yaml




meta:
  run_name: v0705e-bb3
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
