method:
  name: Clean_SAC_Adapter_V1
  args: 
    sb3_init_kwargs:
      verbose: True
    policy_params:
      hypernetwork_kwargs:
        skip_connection: True
        hnet_kwargs:
          hypernetwork_layers: less

mymethod:
  args:
    actor_act_at_end: True
