inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v0857d/v0857d-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_concat_more_comparable_deep_activation.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v0857d-bb3
method:
  load_checkpoint: v0612c-bb3
  load_checkpoint_if_big_seed: v0712c-bb3
