inherit:
- artifacts/config/v0200/v0200-_default.yaml
- artifacts/config/v020x_benchmarks/v1708_3b/v1708_3b-_base.yaml
- artifacts/config/v0200/methods/clean/clean_sac_concat_more_comparable_deep_activation.yaml
meta:
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
  run_name: v1708_3b-bb3
method:
  load_checkpoint: v1708_2b-bb3
train:
  context_encoder:
    args:
      context_dimension: 11
      extra_dimensions: 10
