inherit:
  - artifacts/config/v0200/v0200-_default.yaml
  - artifacts/config/v020x_benchmarks/v0761b/v0761b-_base.yaml
  - artifacts/config/v0200/methods/clean/clean_sac_adapter_v1_less.yaml


method:
  args: 
    policy_params:
      hypernetwork_kwargs:
        put_adapter_at_end: True
        put_adapter_before_last_layer: False
        hnet_kwargs:
          threshold_to_assert_sizes: 20
meta:
  run_name: v0761b-fb11
  message: GenRLise(AdapterLess; ComplexODEBoundedReward)
